### ISSUE TITLE
furtherIssue 2: show recommendations when delete all ingredients

### ISSUE THREAD

**Issue by ryuina** [ryuina/cookit#5]
When delete all added ingredients, 
have to show default recommendations.
<img width="910" alt="2017-05-27 5 52 38" src="https://cloud.githubusercontent.com/assets/14867117/26520011/6d6340ae-4305-11e7-9a1c-139d36e71ebb.png">

**Comment by Kwonyongseok** [comment]
헷갈리지않는다는점에서 좋다고생각

**Comment by JaejinHwang** [comment]
필요한거같슴니다

**Comment by JaejinHwang** [comment]
헐 이게 닫는게 내 창을 끄는게 아니군 ㅈㅅ

**Comment by ryuina** [comment]
완료햇움
